import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import "../styles/globals.css";
import "../styles/globals.scss";

const robotoFlex = Roboto_Flex({
  subsets: ["latin"],          // or ["latin-ext"]
  variable: "--font-roboto",   // optional CSS variable name
  display: "swap",             // good for performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoFlex.variable} antialiased bg-[#EBF7FF]`}
      >
        {children}
      </body>
    </html>
  );
}
